### ISSUE TITLE
Eliminar comentarios

### ISSUE THREAD

**Issue by Nidev-lab** [msdario12/backend-grupo-01-proyecto-final-rc#12]
Buenas! como va? encontre algunos comentarios en el codigo,
![image](https://github.com/msdario12/backend-grupo-01-proyecto-final-rc/assets/53904695/6e50fad7-3b39-4781-b636-f1bd984f527d)
Recuerden, los comentarios no estan vistos como una buena practica , pero en si el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by msdario12** [comment]
Se eliminan los comentarios
