### ISSUE TITLE
Eliminar console.log

### ISSUE THREAD

**Issue by Nidev-lab** [msdario12/backend-grupo-01-proyecto-final-rc#13]
Buenas! encontre algunos console.log que no deberian estar..

![image](https://github.com/msdario12/backend-grupo-01-proyecto-final-rc/assets/53904695/048e13bf-bf16-4988-86a3-1c94bb202e0e)
los console.log en los catch o en donde necesitemos mostrar un error a los usuario por consola, deberian ser console.error

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by msdario12** [comment]
Se eliminan los console.log()
